### ISSUE TITLE
Feature automated body PR links

### ISSUE THREAD

**Issue by sushie1984** [k3rnels-actions/pr-update#165]
### Is your feature request related to a problem? Please describe.

As an software engineer working with multiple team members using staging branch for testing, I want to have an improved and automated visualisation of code changes that my co-workers made.

### Describe the solution you'd like

Assuming we have `pr_body_with_links` input that is explicit set to `true`:

* Every PR that contributed to the `prSource` is linked in the `body` of the automated created feature PR from `prSource` to `prTarget`
* As long as `prTarget` is not merged, every time a new PR is merged into `prSource` the `body` of the feature PR from `prSource` to `prTarget` gets updated and **appends** the new changes 

### Describe alternatives you've considered

Using a company built/closed source bash script solution that is hard to maintain.

### Additional context

See https://github.com/k3rnels-actions/pr-update/pull/166 for possible solutation

**Comment by k3rnelpan1c-dev** [comment]
oh wow, sorry, was apparently not watching this repo myself :man_facepalming:

The idea sounds reasonable and I will check out the PR asap!

**Comment by k3rnelpan1c-dev** [comment]
landed in `v2.0.0` via #171 (thank you for tackling this :wink:)
