### ISSUE TITLE
[B] The `set-output` command is deprecated

### ISSUE THREAD

**Issue by IvekSRC** [k3rnels-actions/pr-update#172]
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by k3rnelpan1c-dev** [comment]
Hi there, thank you for the report!

I am aware of this and have already bumped the `@actions/core` dependency to the required `1.10.0` version on main, yet I want to include the work of *sushie1984* from #171 before I cut the release including this bump.

Hope you can life with this warning for a bit longer :wink: (the official deprecation wont happen till next year btw)

**Comment by IvekSRC** [comment]
Great! Kudos for being up-to-date, thank you!

**Comment by k3rnelpan1c-dev** [comment]
fixed as of `v2.0.0`, thank you for the report :+1:
